CREATE DATABASE IF NOT EXISTS gameboy;

USE gameboy;

CREATE TABLE type(
    t_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    t_name VARCHAR(50) NOT NULL
);

CREATE TABLE games(
    g_ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    pic VARCHAR(50) NOT NULL,
    type_ID INT(11) NOT NULL,
    FOREIGN KEY(type_ID) REFERENCES type(t_id)
);